<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>false</UseWindowsForms>
    <Configurations>Debug;Release;Test</Configurations>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>AutoTrackR2.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="config.ini" />
    <None Remove="Fonts\Orbitron-Bold.ttf" />
    <None Remove="Fonts\Roboto-Regular.ttf" />
    <None Update="themes.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="AutoTrackR2.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="config.ini" />
    <Resource Include="Fonts\Orbitron-Bold.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Roboto-Regular.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
